export const SET_CURRENT_STEP = "SET_CURRENT_STEP";
export const SET_FORM_VALUES = "SET_FORM_VALUES";
export const GET_COUNTRIES = "GET_COUNTRIES";
export const MODAL_SHOW = "MODAL_SHOW";
export const CLOSE_MODAL = "CLOSE_MODAL";
